name: "Godot Android Build"

on:
  push:
    branches:
      - main

jobs:
  export-android:
    name: Android Export
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Keystore
        run: |
          keytool -keyalg RSA -genkeypair -alias androiddebugkey -keypass android -keystore debug.keystore -storepass android -dname "CN=Android Debug,O=Android,C=US" -validity 9999

      - name: Setup Build Directory
        run: mkdir -p build/android

      - name: Export Game
        run: |
          godot --headless --export-release "Android" build/android/game.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/android/game.apk
          
