name: "Godot Android Build"

on:
  push:
    branches:
      - main

jobs:
  export-android:
    name: Android Export
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Godot Export
        uses: firebelley/godot-export@v6.0.0
        with:
          godot_version: 4.2.1
          godot_channel: stable
          export_debug: false
          relative_project_path: ./
          archive_output: false

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Android-APK
          path: build/android/game.apk
          
